### ISSUE TITLE
tighten bounds on text

### ISSUE THREAD

**Issue by vmchale** [haskell/double-conversion#29]
At the moment, `double-conversion` fails to build with text 2.0 

```
Data/Double/Conversion/Text.hs:48:52: error:
    Not in scope: ‘A.maBA’
    Module ‘Data.Text.Array’ does not export ‘maBA’.
   |
48 |       size <- unsafeIOToST $ act (realToFrac val) (A.maBA buf)
   |                                                    ^^^^^^
```

This is because `maBA` has been replaced by [`MutableByteArray`](https://hackage.haskell.org/package/text-2.0/docs/Data-Text-Array.html#t:MArray) as of 2.0!

**Comment by Bodigrim** [comment]
Patch is available in #28

**Comment by Haskell-mouse** [comment]
Damn, I had uploaded a new release with an upper bound for the text package just before you left this comment )

**Comment by Haskell-mouse** [comment]
@Bodigrim, could you please make a new MR into my fork?
https://github.com/Haskell-mouse/double-conversion

**Comment by Bodigrim** [comment]
@Haskell-mouse sorry, I’m on vacation, feel free to cherry pick the commit yourself.

**Comment by Haskell-mouse** [comment]
Thanks, @Bodigrim's. I've adapted your commit for the latest version of the library and made a new minor release.

**Comment by Bodigrim** [comment]
@Haskell-mouse what's the motivation to fork the repo (https://github.com/Haskell-mouse/double-conversion)? This way history of issues and PRs is lost. Since you were granted Hackage upload rights (https://hackage.haskell.org/package/double-conversion/maintainers/), it would be better to grant you permissions for this repo instead. CC @chessai

**Comment by chessai** [comment]
@Haskell-mouse you should have just received an invite to maintain this repo.

**Comment by Haskell-mouse** [comment]
Initially I've just wanted to make PR to this repository. 
I also thought that Bryan is an owner of the repo.

**Comment by Haskell-mouse** [comment]
> @Haskell-mouse you should have just received an invite to maintain this repo.

Wow. Thank you) 
I'll move my changes here.
